### PR TITLE
graalvm is supported for customer service

### PR DESCRIPTION
**Pull request by dartartem**

### CODE REVIEW

**Review by cer — CHANGES_REQUESTED** [review]
Not sure you meant to add the jar

**Comment by dartartem** [comment]
Chris, if you mean this jar:spring-graal-native-feature-0.6.0.BUILD-SNAPSHOT.jar
It is necessary to build graalvm native image.
I will replace to downloading when finish with consumer proxy.

**Comment by cer** [comment]
On Tue, Oct 22, 2019, 8:48 AM Artem Sidorkin <notifications@github.com>
wrote:

> Chris, if you mean this
> jar:spring-graal-native-feature-0.6.0.BUILD-SNAPSHOT.jar
> It is necessary to build graalvm native image.
> I will replace to downloading when finish with consumer proxy.
>

Hmmm... This file isn't in the spring snapshot repository? Where did you
get it from? I'd prefer not to commit a jar because that gets into
licensing issues.

**Comment by dartartem** [comment]
https://github.com/spring-projects-experimental/spring-graal-native
I got it from some example application

**Comment by cer** [comment]
Merged into https://github.com/eventuate-tram-examples/eventuate-tram-examples-micronaut-customers-and-orders/tree/wip-graal branch

**Pull request closed without merging**
